
title: John & Jane's Wedding
description: Celebrate our special day with us!
author: John and Jane
email: johnandjane@example.com
baseurl: ""
url: "https://yourusername.github.io"
theme: minima
plugins:
  - jekyll-feed
