
title: Lewis & Annettes's Wedding
description: Celebrate our special day with us!
author: Lewis and Annette
email: alwedding26@outlook.com
baseurl: "/ALWedding2026/docs"
url: "https://lewissdafni.github.io/ALWedding2026/docs"
theme: minima
plugins:
  - jekyll-feed
